name: 'PR Agent'
description: 'AI agent for pull requests'

inputs:
  github_auth:
    description: 'GitHub authentication token'
    required: true

runs:
  using: "composite"
  steps:
    - name: PR Agent action step
      id: pragent
      uses: Codium-ai/pr-agent@main
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
