name: 'PR Agent'

on:
  workflow_call:

jobs:
  pr_agent:
    name: Run pr agent on every pull request, respond to user comments
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
        issues: write
        pull-requests: write
        contents: write
    steps:
        - id: pragent
          name: PR Agent action step
          uses: FmTod/pr-agent-action@master
          with:
            openai_key: ${{ secrets.OPENAI_KEY }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
